Trait {
	#name : #TimeTravelEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #MolTimeTravel
}

{ #category : #events }
TimeTravelEvents >> restoreFrom: aMemento [

	
]

{ #category : #events }
TimeTravelEvents >> saveForTimeTravel [

	
]

{ #category : #events }
TimeTravelEvents >> startTimeTravel [

	
]

{ #category : #events }
TimeTravelEvents >> stopTimeTravel [

	
]
