Trait {
	#name : #TimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolTimeTravel
}

{ #category : #services }
TimeTravelServices >> creationOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> deletionOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TimeTravelServices >> save: aComponentMemento [

	
]

{ #category : #services }
TimeTravelServices >> saveTheApplication [

	
]
